### ISSUE TITLE
Basic Game Framework

### ISSUE THREAD

**Issue by shahiro770** [shahiro770/CandleLight#4]
Our game currently has jack in it besides a Main Menu that only has a few buttons and no features. Here are the main things that need to happen before we can start getting creative with this game.

![uioverview](https://user-images.githubusercontent.com/6191327/51572549-d1b6c800-1e73-11e9-8fce-da8a023f94ac.jpg)

- [x] Create the system that allows the player to be thrown into a random event
- [x] Create the turn-based battle interface
- [x] Create the other basic UI elements
